function [] = Main_PlotTFC()

clc; close all; clear all

%% INPUT TWO PARAMETERS
t_baseln_lim = [-0.4, -0.1]; % <===================
channelfile = 'ChannelLabels1.locs'; % <=================== 

GUI_PlotTFC(t_baseln_lim,channelfile)

function [] = GUI_PlotTFC (t_baseln_lim,channelfile )

% plot TF-ICA results

%% GUI
bh = figure('unit','normalized','position',[0.2    0.15    0.6    0.7]);
set(bh,'Name',['Plots of Time-frequency/Infomax ICs'],'menubar','none','numbertitle','off')

%% Parameters

%channelfile = 'ChannelLabels_NoFz.locs'; % <=================== 
global TF_IC T_IC PTF_IC PT_IC t f ChannelLabels t_baseln_lim pathname filename channelfile;

%% Load ICA results
% FIRST load
sub_loadtfica([],[],pwd,[]);

%% panels
bh_file = uibuttongroup('Parent',bh,'Title','Current File','fontsize',16,'fontweight','bold',...
            'titleposition','lefttop','Position',[.3 .82 .62 .17]);
h_file = uicontrol('Parent',bh_file,'Style','text','String',filename,...
                'Units','normalized','Position',[0.02 0 0.98 .8],...,
                'horizontalalignment','center','fontsize',16);   

h_openfile = uicontrol('Parent',bh,'Style','pushbutton','String','Load a File','fontsize',18,'fontweight','bold',...
            'Units','normalized','Position',[.08 .82 .2 .1],'Callback',{'sub_loadtfica',pathname,h_file});

% two backgrouds
bgh_tf = uibuttongroup('Parent',bh,'Title','Fourier-ICA','fontsize',16,'fontweight','bold',...
            'titleposition','centertop','Position',[.1 .1 .35 .3]);
bgh_t  = uibuttongroup('Parent',bh,'Title','Infomax-ICA','fontsize',16,'fontweight','bold',...
            'titleposition','centertop','Position',[.55 .1 .35 .3]);   
bgh_ptf = uibuttongroup('Parent',bh,'Title','Probabilistic Fourier-ICA','fontsize',16,'fontweight','bold',...
            'titleposition','centertop','Position',[.1 .45 .35 .3]);
bgh_pt  = uibuttongroup('Parent',bh,'Title','Probabilistic Infomax-ICA','fontsize',16,'fontweight','bold',...
            'titleposition','centertop','Position',[.55 .45 .35 .3]); 
        
% P-TF-ICA: Topo     
pbh_ptf_topo = uicontrol('Parent',bgh_ptf,'Style','pushbutton','String','Topography',...
                'Units','normalized','Position',[.1 .1 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Fourier-ICA','topo',channelfile});   
% P-TF-ICA: TFR
pbh_ptf_tfr  = uicontrol('Parent',bgh_ptf,'Style','pushbutton','String','Time-Frequency Representation',...
                'Units','normalized','Position',[.1 .7 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Fourier-ICA','tfr',channelfile});        
% P-TF-ICA: ERP
pbh_ptf_eeg  = uicontrol('Parent',bgh_ptf,'Style','pushbutton','String','Time-domain EEG/ERP',...
                'Units','normalized','Position',[.1 .4 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Fourier-ICA','eeg',channelfile}); 

% P-Infomax-ICA: Topo            
pbh_pt_topo  = uicontrol('Parent',bgh_pt,'Style','pushbutton','String','Topography',...
                'Units','normalized','Position',[.1 .1 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Infomax-ICA','topo',channelfile});   
% P-Infomax-ICA: TFR            
pbh_pt_tfr  = uicontrol('Parent',bgh_pt,'Style','pushbutton','String','Time-Frequency Representation',...
                'Units','normalized','Position',[.1 .4 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Infomax-ICA','tfr',channelfile});
% P-Infomax-ICA: EEG
pbh_pt_eeg  = uicontrol('Parent',bgh_pt,'Style','pushbutton','String','Time-domain EEG/ERP',...
                'Units','normalized','Position',[.1 .7 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Probabilistic Infomax-ICA','eeg',channelfile});
            
            
% TF-ICA: Topo     
pbh_tf_topo = uicontrol('Parent',bgh_tf,'Style','pushbutton','String','Topography',...
                'Units','normalized','Position',[.1 .1 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Fourier-ICA','topo',channelfile});   
% TF-ICA: TFR
pbh_tf_tfr  = uicontrol('Parent',bgh_tf,'Style','pushbutton','String','Time-Frequency Representation',...
                'Units','normalized','Position',[.1 .7 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Fourier-ICA','tfr',channelfile});        
% TF-ICA: ERP
pbh_tf_eeg  = uicontrol('Parent',bgh_tf,'Style','pushbutton','String','Time-domain EEG/ERP',...
                'Units','normalized','Position',[.1 .4 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Fourier-ICA','eeg',channelfile});   

% Infomax-ICA: Topo            
pbh_t_topo  = uicontrol('Parent',bgh_t,'Style','pushbutton','String','Topography',...
                'Units','normalized','Position',[.1 .1 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Infomax-ICA','topo',channelfile});   
% Infomax-ICA: TFR            
pbh_t_tfr  = uicontrol('Parent',bgh_t,'Style','pushbutton','String','Time-Frequency Representation',...
                'Units','normalized','Position',[.1 .4 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Infomax-ICA','tfr',channelfile});
% Infomax-ICA: EEG
pbh_t_eeg  = uicontrol('Parent',bgh_t,'Style','pushbutton','String','Time-domain EEG/ERP',...
                'Units','normalized','Position',[.1 .7 .8 .2],...
                'Callback', {'sub_plotallic',filename,'Infomax-ICA','eeg',channelfile});
